services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mercadolibre
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
